[2~[2~go get github.com/golang/lint/golint
go get github.com/kisielk/errcheck
go get golang.org/x/tools/cmd/benchcmp
go get github.com/cespare/prettybench
go get github.com/ajstarks/svgo/benchviz
go get golang.org/x/tools/cmd/goimports
go get code.google.com/p/rog-go/exp/cmd/godef
go get code.google.com/p/rog-go/exp/cmd/godef
go get github.com/nsf/gocode
go get github.com/kisielk/godepgraph
